rust_library(
    name = "cli",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    deps = [
        "//crates/lib/utils:utils",
        "//third-party:anyhow",
        "//third-party:clap",
        "//third-party:derive_more",
        "//third-party:getset",
    ],
    visibility = ["PUBLIC"],
)

rust_test(
    name = "cli_test",
    srcs = glob(["tests/**/*.rs"]),
    edition = "2021",
    deps = [
        ":cli",
    ],
    visibility = ["PUBLIC"],
)
