[package]
name = "bkg"
version = "0.1.0"
edition = "2021"
authors = ["pulanski"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
driver = { path = "../../lib/driver" }
utils = { path = "../../lib/utils" }
watch = { path = "../../lib/watch" }

miette = { workspace = true }
