[package]
name = "pb"
version = "0.1.0"
edition = "2021"
authors = ["pulanski"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
driver = { path = "../../lib/driver" }
utils = { path = "../../lib/utils" }
watch = { path = "../../lib/watch" }

derive_more = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true }
lazy_static = { workspace = true }
miette = { workspace = true }
owo-colors = { workspace = true }
progress = { workspace = true }
rand = { workspace = true }
smartstring = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-indicatif = { workspace = true }
tracing-subscriber = { workspace = true }
ulid = { workspace = true }
