[package]
name = "incremental_salsa"
version = "0.1.0"
edition = "2021"
authors = ["pulanski"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
crossbeam = { workspace = true }
crossterm = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true }
miette = { workspace = true }
parking_lot = { workspace = true }
# rayon = { workspace = true }
crossbeam-channel = { workspace = true }
eyre = { workspace = true }
notify-debouncer-mini = { workspace = true }
salsa = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# [dev-dependencies]
# expect-test = "1.4.0"
